
import type { AppData, Translations } from './types';

export const appData: AppData = {
    sudan: {
        name: "Sudan",
        landscape: {
            penetration: "28.7%",
            socialUsers: "13.5 Million",
            keyInsight: "Facebook Dominance (89%)",
            platforms: {
                labels: ['Facebook', 'Twitter', 'YouTube', 'Instagram', 'Pinterest', 'LinkedIn', 'TikTok', 'WhatsApp'],
                data: [89.39, 9.28, 0.82, 0.4, 0.07, 0.03, 0.05, 0.06],
                colors: ['#4267B2', '#1DA1F2', '#FF0000', '#C13584', '#E60023', '#0A66C2', '#000000', '#25D366']
            }
        },
        behavior: {
            peakTimes: [
                { time: "Morning (9 AM - 11 AM)", platforms: "Facebook, Twitter", icon: "SunIcon" },
                { time: "Afternoon (1 PM - 3 PM)", platforms: "Facebook, Twitter", icon: "BuildingOfficeIcon" },
                { time: "Evening (7 PM - 10 PM)", platforms: "YouTube, Facebook", icon: "MoonIcon" }
            ],
            engagingContent: [
                { nameKey: "visualContent", icon: "PhotoIcon" },
                { nameKey: "breakingNews", icon: "NewspaperIcon" },
                { nameKey: "politicalDiscourse", icon: "MegaphoneIcon" },
                { nameKey: "humorSatire", icon: "FaceSmileIcon" },
                { nameKey: "localContent", icon: "MapPinIcon" },
                { nameKey: "personalStories", icon: "HeartIcon" }
            ]
        },
        agriculture: {
            topics: [
                { titleKey: "knowledgeDissemination", descriptionKey: "knowledgeDisseminationDesc" },
                { titleKey: "marketAccess", descriptionKey: "marketAccessDesc" },
                { titleKey: "foodSecurity", descriptionKey: "foodSecurityDesc" }
            ],
            platforms: [
                { name: "WhatsApp / Facebook", descriptionKey: "whatsappFacebookDesc", icon: "ChatBubbleLeftRightIcon" },
                { name: "YouTube", descriptionKey: "youtubeDesc", icon: "PlayCircleIcon" }
            ]
        },
        calendar: {
            activeDays: [0, 1, 2, 3, 4, 5, 6],
            activePeriods: {
                0: ['9 AM - 11 AM', '1 PM - 3 PM'], 
                1: ['9 AM - 11 AM', '1 PM - 3 PM', '7 PM - 10 PM'], 
                2: ['9 AM - 11 AM', '1 PM - 3 PM', '7 PM - 10 PM'], 
                3: ['9 AM - 11 AM', '1 PM - 3 PM', '7 PM - 10 PM'], 
                4: ['9 AM - 11 AM', '1 PM - 3 PM', '7 PM - 10 PM'], 
                5: ['7 PM - 10 PM'], 
                6: ['7 PM - 9 PM']
            },
            facebookActiveDays: [0, 1, 2, 3, 4, 5, 6],
            facebookPosts: [
                { date: '07-21', title: 'Pinned Post: Aid & Resources', description: 'A post with a directory of local seed suppliers and a link to a community-sourced guide on vegetable planting.' },
                { date: '07-24', title: 'Community Group Promotion', description: 'Actively create and promote a group like the "Sudan Vegetable Gardeners Network" for peer-to-peer support.' },
                { date: '07-28', title: 'Live Q&A', description: 'A scheduled Live session with a respected local agronomist on vegetable planting techniques for the current season.' },
                { date: '07-31', title: 'Informative Post', description: 'A detailed text-and-photo post explaining the benefits of a new, drought-resistant tomato variety available locally.' },
                { date: '08-04', title: 'Event Creation', description: 'Create a Facebook Event for a local "Farmers\' Market Day" to showcase vegetable produce.' },
                { date: '08-07', title: 'Shared Article', description: 'Share a link to a story from a local blog about the importance of home gardens for food security.' },
                { date: '08-11', title: 'Photo Album: Kassala Seed Bank', description: 'A full album documenting a local vegetable seed bank.' },
                { date: '08-14', title: 'Poll: Most Important Seed Quality', description: 'What is the most important quality in a vegetable seed for you? (Options: Drought Resistance, High Yield, Pest Resistance, Taste).' },
                { date: '08-18', title: 'Call for Stories', description: 'Share a story about a vegetable seed variety your family has been planting for generations.' },
                { date: '08-21', title: 'Weekly Update', description: 'A regular text post summarizing key gardening news, vegetable seed availability, and weather forecasts.' },
                { date: '08-25', title: 'Link to Resources', description: 'A post linking to a downloadable PDF guide on organic pest control for vegetable seedlings.' },
                { date: '08-28', title: 'Success Story Feature', description: 'A long-form post telling the personal story of a farmer who had a successful vegetable harvest using improved seeds.' },
                { date: '09-01', title: 'Discussion Starter', description: 'What is the most important lesson your elders taught you about when to plant your vegetable garden?' },
                { date: '09-04', title: 'Video: Certified Seed', description: 'A re-upload of a short YouTube documentary on "What is a Quality Vegetable Seed?" for native viewing.' },
                { date: '09-08', title: 'Community Partnership Announcement', description: 'A post announcing a collaboration between a local cooperative and a local business to preserve vegetable varieties.' },
                { date: '09-11', title: 'Fact-Check Post', description: 'A post debunking a recent rumor about certain vegetable seeds being unsafe.' },
                { date: '09-15', title: 'Meet a Leader', description: 'A profile of the head of a local vegetable seed-saving cooperative.' },
                { date: '09-18', title: 'Photo Album: The Children\'s Garden', description: 'A hopeful album showing children learning how to plant vegetable seeds.' },
                { date: '09-22', title: 'Live Audio Room', description: 'Host a discussion on "The Challenges of Getting Vegetable Seeds to Market".' },
                { date: '09-25', title: 'Infographic Share', description: 'Post a full-size infographic on "How to Create a Seed Starting Mix for Vegetables".' },
                { date: '09-29', title: 'Call for Questions', description: 'We are meeting with a major local seed supplier next week. What questions do you have for them?' },
                { date: '10-02', title: 'Historical Post', description: '"On this day in history..." featuring a significant event in Sudan\'s horticultural past.' },
                { date: '10-06', title: 'Marketplace Post', description: 'Facilitate a virtual "Vegetable Seed Exchange" where verified members can post seeds they have for trade.' },
                { date: '10-09', title: 'Safety Alert', description: 'A post warning about a specific disease or pest outbreak affecting tomatoes.' },
                { date: '10-13', title: 'From the Diaspora', description: 'Share messages of support and fundraising efforts from diaspora groups to buy vegetable seeds for communities back home.' },
                { date: '10-16', title: 'Job Posting', description: 'Share opportunities for work at local nurseries or seed supply businesses.' }
            ],
            tiktokActiveDays: [0, 2, 3, 5, 6],
            tiktokPosts: [
                { date: '07-22', title: 'Quick Tip', description: '15-second seed spacing tip for Okra.' },
                { date: '07-25', title: 'Satisfying Video', description: 'Slicing a perfectly ripe tomato grown from your own garden.' },
                { date: '07-29', title: 'Quick How-To', description: 'Test tomato seed viability with a paper towel in 5 seconds.' },
                { date: '08-01', title: 'Relatable Humor', description: 'A short skit about protecting your tomato seedlings from hungry goats.' },
                { date: '08-05', title: 'Trending Sound', description: 'A farmer lip-syncing to a popular song while showing off their sprouting vegetable seedlings.' },
                { date: '08-08', title: 'Quick Question', description: 'A text-on-screen poll: "Tomatoes or Onions?" with visuals of the two vegetables.' },
                { date: '08-12', title: 'Mini-Vlog', description: '"My Morning: Watering the Vegetable Seedbeds" - a 30-second montage.' },
                { date: '08-15', title: 'DIY', description: 'Making a simple seed-starting pot from newspaper for vegetables.' },
                { date: '08-19', title: 'Inspirational', description: 'A short clip of a dry patch of land, then a transition to it being a lush vegetable garden.' },
                { date: '08-22', title: 'Community', description: 'A quick pan of a group of people working together to plant a community vegetable garden.' },
                { date: '08-26', title: 'Food', description: 'The satisfying sizzle of onions frying in a pan.' },
                { date: '08-29', title: 'Transition', description: 'A "vegetable seed to seedling" transition.' },
                { date: '09-02', title: 'Dance', description: 'A short, energetic traditional dance celebrating the vegetable planting season.' },
                { date: '09-05', title: 'Animal Video', description: 'A goat playfully trying to eat seedlings from a pot.' },
                { date: '09-09', title: '"Things in my vegetable seed bag"', description: 'A quick reveal of essential items for planting.' },
                { date: '09-12', title: 'How-To', description: 'Sharpening a hoe for weeding vegetable beds.' },
                { date: '09-16', title: 'Relatable Skit', description: 'When you see the first tomato flower...' },
                { date: '09-19', title: 'Quick Build', description: 'Assembling a simple drip irrigation line for vegetable seedlings.' },
                { date: '09-23', title: '"POV: You\'re a tiny tomato seed"', description: 'A dark screen that gets brighter and greener.' },
                { date: '09-26', title: 'Satisfying', description: 'A perfect row of newly planted vegetable seeds.' },
                { date: '09-30', title: 'Humor', description: 'A skit about trying to explain germination to a city cousin using vegetable seeds.' },
                { date: '10-03', title: 'Quick Tour', description: 'A 10-second tour of our community vegetable seed bank.' },
                { date: '10-07', title: '"Unboxing"', description: 'Opening a new packet of vegetable seeds from a local shop.' },
                { date: '10-10', title: 'Sports', description: 'A quick clip of a football game after a day of planting the garden.' },
                { date: '10-14', title: '"My favorite sound"', description: 'The sound of rain on a vegetable garden.' },
                { date: '10-17', title: 'Quick Hack', description: 'Using ash to protect vegetable seedlings from pests.' }
            ],
            instagramActiveDays: [0, 1, 3, 4, 6],
            instagramPosts: [
                { date: '07-20', title: 'Photo Series: "Hands of the Harvest"', description: "Close-up, expressive photos of farmers' hands holding vegetable seeds." },
                { date: '07-23', title: 'Reel: "From Dust to Green"', description: 'A time-lapse of a community vegetable seedbed sprouting.' },
                { date: '07-27', title: 'Infographic: "5 Tips for Better Tomato Germination"', description: 'Simple, visual tips for ensuring more seeds sprout successfully.' },
                { date: '07-30', title: 'Quote Graphic: Farmer on Hope', description: 'A powerful quote from a farmer on the hope contained within a single vegetable seed.' },
                { date: '08-03', title: 'Story Poll: "Which vegetable seed?"', description: 'Which vegetable seed are you planting this season? (Options: Tomato, Onion, Okra, Eggplant).' },
                { date: '08-06', title: 'Carousel: "A Day with a Seed Saver"', description: 'A visual step-by-step of a farmer carefully selecting and storing tomato seeds.' },
                { date: '08-10', title: 'Reel: "The Sound of Sowing"', description: 'A short, hopeful video focusing on the sound and sight of vegetable seeds being planted.' },
                { date: '08-13', title: 'Infographic: "The Life of a Vegetable Seed"', description: 'A simple flowchart explaining the journey from a seed packet to a mature plant.' },
                { date: '08-17', title: 'Photo: "A Handful of Hope"', description: 'A graphic featuring a photo of a child holding a handful of okra seeds.' },
                { date: '08-20', title: 'Story Q&A: "Ask a Master Gardener"', description: 'Host an "Ask a Master Gardener" session with a respected local farmer.' },
                { date: '08-24', title: 'Carousel: "Sudanese Proverbs of the Garden"', description: 'Each slide features a proverb about planting a garden in Arabic calligraphy.' },
                { date: '08-27', title: 'Reel: "Making Vegetable Seed Balls"', description: 'A quick, satisfying video of mixing clay, compost, and seeds for easy planting.' },
                { date: '08-31', title: 'Photo: "A Child\'s First Tomato Plant"', description: 'A single, powerful photo of a child looking at a tiny seedling they planted.' },
                { date: '09-03', title: 'Infographic: "Why Local Vegetable Seeds Matter"', description: 'Visualizing the benefits of planting locally-adapted vegetable varieties.' },
                { date: '09-07', title: 'Before/After: Vegetable Patch', description: 'A side-by-side photo of a vegetable patch before and after planting.' },
                { date: '09-10', title: 'Reel: "Weaving Seed Pouches"', description: 'A craft tutorial showing how to weave small pouches for storing vegetable seeds.' },
                { date: '09-14', title: 'Quote Graphic: Community Leader', description: 'Featuring a powerful statement from a community leader about the importance of vegetable seed sovereignty.' },
                { date: '09-17', title: 'Map Graphic: Vegetable Suitability', description: 'A simple map showing which regions are best suited for growing specific vegetables like tomatoes or cucumbers.' },
                { date: '09-21', title: 'Carousel: "Meet the Team at a Local Seed Shop"', description: 'Introducing the staff of a local business that sells quality seeds.' },
                { date: '09-24', title: 'Reel: "A Moment of Growth"', description: 'A short, close-up clip of a vegetable seedling breaking through the soil.' },
                { date: '09-28', title: 'Photo: "The Elder\'s Seeds"', description: 'A respectful portrait of an elder farmer holding up heirloom vegetable seeds.' },
                { date: '10-01', title: 'Infographic: "Why Cooperatives Help"', description: 'Explaining the benefits of forming co-ops to buy seeds in bulk.' },
                { date: '10-05', title: 'Story Takeover: Field Officer', description: 'A successful local farmer takes over the account for a day to share tips.' },
                { date: '10-08', title: 'Reel: "The Journey of Water"', description: 'Tracing water from a well to a newly planted vegetable patch.' },
                { date: '10-12', title: 'Photo: "Sunset over a Planted Garden"', description: 'A beautiful, hopeful image of a landscape prepared for growth.' },
                { date: '10-15', title: 'Carousel: "Sudan\'s At-Risk Vegetables"', description: 'Highlighting unique, indigenous vegetable varieties that are at risk of being lost.' }
            ],
            linkedinActiveDays: [1, 2, 3, 4, 5],
            linkedinPosts: [
                { date: '07-14', title: 'Article: Horticulture as a Pillar of Stability', description: 'The Unseen Economic Engine in Wartime Sudan.' },
                { date: '07-15', title: 'Profile Spotlight: Sudanese Horticulturist', description: 'On the long-term impacts of conflict on Sudan\'s vegetable genetic diversity.' },
                { date: '07-16', title: 'NGO Impact Report Summary', description: 'On the collapse of the formal vegetable seed sector and its effect on nutrition.' },
                { date: '07-17', title: 'Call for Partnership', description: 'A post from a local NGO seeking international partners for a new community vegetable seed bank project.' },
                { date: '07-18', title: 'Industry Analysis: Seed Shortage', description: 'A Deep Dive into Sudan\'s Vegetable Seed Shortage.' },
                { date: '07-21', title: 'Professional Story: Horticulturist to Aid Worker', description: 'The Forced Career Change of Sudan\'s Agricultural Scientists.' },
                { date: '07-22', title: 'Policy Discussion: Rebuilding the Seed System', description: 'A Policy Framework for Post-Conflict Sudan.' },
                { date: '07-23', title: 'Investment Pitch: Seed Multiplication', description: 'Profile of a local enterprise seeking investment for a scalable vegetable seed multiplication solution.' },
                { date: '07-24', title: 'Round-up: Must-Read Reports', description: '5 Must-Read Reports on Sudan\'s Food Security and Vegetable Seed Systems This Month.' },
                { date: '07-25', title: 'Company Update: AAAID', description: 'An update from AAAID on their efforts to support the Sudanese vegetable seed sector.' },
                { date: '07-28', title: 'Expert Opinion: Resilient Varieties', description: 'An article by an agronomist on the most resilient and nutrient-dense vegetable varieties for Sudan.' },
                { date: '07-29', title: 'Infographic: Decline in Certified Seed Use', description: 'A professional infographic detailing the decline in certified vegetable seed usage and its impact on national nutrition.' },
                { date: '07-30', title: 'Webinar Announcement: Seed Sovereignty', description: 'Announce a webinar on "The Future of Vegetable Seed Sovereignty in Post-Conflict Sudan."' },
                { date: '07-31', title: 'A Call to the Diaspora', description: 'An article on how Sudanese ag-professionals abroad can help rebuild vegetable seed systems.' },
                { date: '08-01', title: 'Case Study: Community Seed Bank Model', description: 'A detailed case study of a successful community vegetable seed bank model in a similar conflict zone.' },
                { date: '08-04', title: 'White Paper: Low-Cost Tech', description: 'The Role of Low-Cost Tech in Vegetable Seed Viability Testing: Lessons from Sudan.' },
                { date: '08-05', title: 'Profile: Head of Farmers\' Union', description: 'Highlighting their advocacy for access to quality vegetable seeds.' },
                { date: '08-06', title: 'Press Release Summary: FAO/WFP', description: 'A summary of a recent press release from the FAO or WFP regarding their vegetable seed distribution operations.' },
                { date: '08-07', title: 'Networking Post', description: 'Seeking connections with experts in vegetable seed system development and conflict-zone horticulture.' },
                { date: '08-08', title: 'Analysis: Geopolitical Factors', description: 'The Geopolitical Factors Impacting Vegetable Seed Aid Delivery in Sudan.' },
                { date: '08-11', title: 'The Business of Aid', description: 'An article exploring the logistics of humanitarian vegetable seed supply chains.' },
                { date: '08-12', title: 'Profile of an Institution: HRC', description: 'A post detailing the history and current struggles of the Horticultural Research Corporation of Sudan.' },
                { date: '08-13', title: 'Data Story: Seeds and Nutrition', description: 'A post visualizing the link between access to quality vegetable seeds and reduced child malnutrition.' },
                { date: '08-14', title: 'Thought Leadership: Beyond Aid', description: 'A Framework for Building Sustainable, Farmer-Led Vegetable Seed Systems in Sudan.' },
                { date: '08-15', title: 'Project Showcase: Climate-Resilient Varieties', description: 'A detailed overview of a project promoting climate-resilient tomato and onion varieties.' },
                { date: '08-18', title: 'The Talent Drain', description: 'An article on how the conflict is affecting the availability of skilled plant breeders specializing in vegetables.' },
                { date: '08-19', title: 'Legal Analysis: IP Rights', description: 'A lawyer\'s perspective on the legal challenges of intellectual property for vegetable seeds developed by local communities.' },
                { date: '08-20', title: 'Rebuilding Institutions', description: 'A post on the importance of re-establishing horticultural research stations.' },
                { date: '08-21', title: 'Call for Mentors', description: 'A program connecting retired horticulturists with young Sudanese farmers.' },
                { date: '08-22', title: 'The Gendered Impact of Crisis', description: 'An analysis of how conflict disproportionately affects female farmers, who are often the primary vegetable seed savers.' },
                { date: '08-25', title: 'Company Profile: Seed Company', description: 'A feature on a company specializing in vegetable seeds, detailing its role and challenges.' },
                { date: '08-26', title: 'The Ethics of Aid', description: 'A reflection on the challenges of distributing vegetable seeds without creating dependency.' },
                { date: '08-27', title: 'Technology Review: Mobile Apps', description: 'An analysis of using mobile apps for tracking vegetable seed distribution in a low-connectivity environment.' },
                { date: '08-28', title: 'A Path to Peace', description: 'An article arguing for the role of cooperative vegetable gardening in peace-building efforts.' },
                { date: '08-29', title: 'Historical Perspective', description: 'How Past Famines in Sudan Inform Today\'s Vegetable Seed Security Strategies.' },
                { date: '09-01', title: 'The Power of Remittances', description: 'An analysis of how money from the diaspora is enabling families to purchase vegetable seeds.' },
                { date: '09-02', title: 'Book Recommendation', description: 'Suggest a book on the history of horticulture in the Sahel or the science of vegetable seed saving.' },
                { date: '09-03', title: 'The Future of Water for Seeds', description: 'A deep dive into water security challenges and the need for drought-resistant vegetable varieties.' },
                { date: '09-04', title: 'University Collaboration', description: 'A post highlighting a partnership to preserve vegetable crop genetic diversity.' },
                { date: '09-05', title: 'Logistics Under Fire', description: 'An interview with a logistics expert on the challenges of transporting vegetable seeds to remote areas.' },
                { date: '09-08', title: 'The Psychology of Planting', description: 'An article on how planting a vegetable garden maintains hope in communities.' },
                { date: '09-09', title: 'From the Ground Up', description: 'A series profiling new, small businesses focused on vegetable seed multiplication.' },
                { date: '09-10', title: 'The Role of Local Government', description: 'An analysis of the challenges facing state-level ministries of agriculture in regulating vegetable seed quality.' },
                { date: '09-11', title: 'A Vision for 2030', description: 'A forward-looking article on what a rebuilt Sudanese vegetable sector could look like.' },
                { date: '09-12', title: 'Open Question', description: 'What is the single most critical innovation needed to secure Sudan\'s vegetable seed sovereignty right now?' },
            ],
            youtubeActiveDays: [0, 3, 4, 5, 6],
            youtubePosts: [
                { date: '07-23', title: 'Series: "Voices of Resilience"', description: 'Short (3-5 minute) audio interviews with static portraits of farmers sharing stories of how they saved tomato and okra seeds.' },
                { date: '07-26', title: 'Animated History: "The Gardens of Khartoum"', description: 'A simple animated video explaining the historical significance of urban and peri-urban vegetable gardens.' },
                { date: '07-30', title: 'Tutorial: "Solar Pump Maintenance"', description: 'A practical, step-by-step guide on maintaining small solar-powered irrigation pumps for vegetable seedbeds.' },
                { date: '08-02', title: 'Success Story: "Salwa\'s Roadside Stall"', description: 'A photo-documentary telling the story of women creating small businesses selling produce grown from their own saved vegetable seeds.' },
                { date: '08-06', title: 'Cooking Show: "From Seed to Shakshouka"', description: 'A series showing how to prepare nutritious meals from garden staples like tomatoes, onions, and peppers.' },
                { date: '08-09', title: 'Expert Q&A (Audio Only)', description: 'An audio recording of a Q&A with a seasoned local farmer answering questions about vegetable seed-borne diseases.' },
                { date: '08-13', title: 'Weekly News Roundup (Audio)', description: 'A 5-minute audio summary of community agricultural news, including tips on where to find the best vegetable seeds.' },
                { date: '08-16', title: 'Tribute: "The Vegetable Seed Keepers"', description: 'A powerful photo-essay telling the story of farmers who have become custodians of rare, local vegetable seed varieties.' },
                { date: '08-20', title: 'Educational: "What is a Certified Vegetable Seed?"', description: 'A simple animated video explaining why using certified tomato or onion seeds is crucial for a successful harvest.' },
                { date: '08-23', title: 'Community Spotlight: "Kassala\'s Onion Success"', description: 'A short feature on how a local farmers\' forum is helping farmers source and share high-quality onion seeds.' },
                { date: '08-27', title: 'Health Guide: "Clean Water for Seedlings"', description: 'A visual guide on simple water purification techniques to prevent fungal growth in vegetable seedbeds.' },
                { date: '08-30', title: 'Market Update (Audio)', description: 'A weekly audio broadcast on the prices and availability of key vegetable seed types (tomato, okra, onion).' },
                { date: '09-03', title: 'Series: "Songs of the Vegetable Garden"', description: 'Featuring traditional Sudanese songs related to planting vegetables, with images of seeds and plants.' },
                { date: '09-06', title: 'DIY Guide: "Building a Seed Storage Jar"', description: 'A step-by-step visual guide to creating a low-cost, airtight container to protect vegetable seeds.' },
                { date: '09-10', title: 'Profile: "The Entrepreneur\'s Vegetable Seed Delivery"', description: 'A "day in the life" photo-narrative of a local entrepreneur who runs a small business delivering vegetable seeds.' },
                { date: '09-13', title: 'Language Lesson: "Seed in Your Dialect"', description: 'Short videos explaining the word for "tomato seed" and "harvest" in various Sudanese languages.' },
                { date: '09-17', title: 'Historical Deep Dive: "Ancient Vegetables of Nubia"', description: 'Exploring the millennia-old cultivation of native vegetables in Nubia with archival images.' },
                { date: '09-20', title: 'Technology Explained: "Reading a Seed Packet"', description: 'A simple animated video explaining the information on a certified seed packet.' },
                { date: '09-24', title: 'Cooperative Spotlight: "The Power of Bulk Buying"', description: 'A feature on how farming cooperatives are helping communities pool resources to purchase vegetable seeds.' },
                { date: '09-27', title: 'Mental Health for Farmers', description: 'An audio session with a community elder on coping with the anxiety of planting a new vegetable crop.' },
                { date: '10-01', title: 'Children\'s Storytime: "The Magical Tomato Seed"', description: 'An animated folktale about a magical tomato seed that feeds a whole village.' },
                { date: '10-04', title: 'Livestock Health: Fodder Crops', description: 'A visual guide to identifying quality fodder crops that can be grown alongside vegetables.' },
                { date: '10-08', title: 'Tool Repair Workshop: Vegetable Beds', description: 'Simple video tutorials on how to adapt and repair hand-tools for creating vegetable beds.' },
                { date: '10-11', title: 'For the Diaspora: "Planting a Piece of Home"', description: 'Profiling Sudanese diaspora who are growing native Sudanese vegetables like roselle (karkade).' },
                { date: '10-15', title: 'Myth vs. Fact: Vegetable Seed Edition', description: 'A short video debunking common misinformation about vegetable seeds.' },
                { date: '10-18', title: 'Tribute to Women Farmers', description: 'A photo montage celebrating the central role of women in selecting and saving vegetable seeds.' }
            ],
            whatsappActiveDays: [5, 6],
            whatsappPosts: [
                { date: '07-19', title: "WhatsApp: Good morning, farmers! ☀️", description: "When we see this bountiful harvest, we know your hard work has paid off. Fertile land brings prosperity to all. Congratulations! (Image of a bountiful harvest)" },
                { date: '08-02', title: "WhatsApp: Our children deserve the best, and good land provides it. 🌱", description: "Their health starts in our green fields. (Short video of a child eating fresh fruit, then a green field)" }
            ]
        }
    },
    oman: {
        name: "Oman",
        landscape: {
            penetration: "97.8%",
            socialUsers: "3.97 Million",
            keyInsight: "Diverse Market & Visual Platforms",
            platforms: {
                labels: ['Facebook', 'Twitter', 'Instagram', 'Pinterest', 'YouTube', 'LinkedIn', 'TikTok', 'WhatsApp'],
                data: [52.81, 21.87, 16.98, 3.76, 3.61, 0.54, 0.25, 0.38],
                colors: ['#4267B2', '#1DA1F2', '#C13584', '#E60023', '#FF0000', '#0A66C2', '#000000', '#25D366']
            }
        },
        behavior: {
            peakTimes: [
                { time: "Morning (10 AM - 11 AM)", platforms: "Twitter, LinkedIn", icon: "SunIcon" },
                { time: "Afternoon (1 PM - 4 PM)", platforms: "Instagram, Facebook", icon: "BuildingOfficeIcon" },
                { time: "Evening (8 PM - 9 PM)", platforms: "Instagram, YouTube", icon: "MoonIcon" }
            ],
            engagingContent: [
                { nameKey: "visualStorytelling", icon: "CameraIcon" },
                { nameKey: "shortFormVideo", icon: "DevicePhoneMobileIcon" },
                { nameKey: "localContent", icon: "FlagIcon" },
                { nameKey: "influencerMarketing", icon: "SparklesIcon" },
                { nameKey: "thoughtLeadership", icon: "LightBulbIcon" },
                { nameKey: "directEngagement", icon: "ChatBubbleLeftEllipsisIcon" }
            ]
        },
        agriculture: {
            topics: [
                { titleKey: "waterScarcity", descriptionKey: "waterScarcityDesc" },
                { titleKey: "techInnovations", descriptionKey: "techInnovationsDesc" },
                { titleKey: "digitalMarketing", descriptionKey: "digitalMarketingDesc" }
            ],
            platforms: [
                { name: "Instagram", descriptionKey: "instagramDesc_oman", icon: "CameraIcon" },
                { name: "Twitter / LinkedIn", descriptionKey: "twitterLinkedinDesc_oman", icon: "LinkIcon" }
            ]
        },
        calendar: {
            activeDays: [0, 1, 2, 3, 4, 5, 6],
            activePeriods: {
                0: ['6 PM - 9 PM', '8 PM (Instagram)'], 1: ['9 AM - 11 AM', '1 PM - 2 PM'], 2: ['9 AM - 11 AM', '1 PM - 2 PM'], 3: ['9 AM - 11 AM', '1 PM - 2 PM'], 4: ['9 AM - 11 AM', '1 PM - 2 PM', '6 PM - 9 PM'], 5: ['6 PM - 9 PM'], 6: ['8 PM (Instagram)', '6 PM - 9 PM']
            },
            facebookActiveDays: [0, 1, 2, 3, 4, 5, 6],
            facebookPosts: [
                { date: '07-20', title: 'Photo Album: "Celebrating Oman\'s Agricultural Heritage"', description: 'A gallery of photos from vegetable farms across the country.' },
                { date: '07-23', title: 'Event Promotion: Community Seed Swap', description: 'Create a Facebook Event for a "Community Vegetable Seed Swap".' },
                { date: '07-27', title: 'Link Share: Local Newspaper Article', description: 'Share an article from a local newspaper about a farmer preserving rare vegetable seeds.' },
                { date: '07-30', title: 'Discussion Starter: Heirloom Vegetables', description: 'What heirloom vegetable does your family love to grow? Share a photo!' },
                { date: '08-03', title: 'Live Video: Seed Research Lab Opening', description: 'A live broadcast from the opening of a new private vegetable seed research lab.' },
                { date: '08-06', title: 'Informative Post: National Vision', description: 'A long-form post explaining the national vision for vegetable seed security and food diversification.' },
                { date: '08-10', title: 'Family-Oriented Content: "Easy-to-Grow Vegetables"', description: 'Top 5 Easy-to-Grow Vegetables for Kids in Oman.' },
                { date: '08-13', title: 'Community News: Garden Success Story', description: 'Share a story about a local community that has successfully started a community vegetable garden.' },
                { date: '08-17', title: 'Poll: "New Vegetable Excitement"', description: 'Which new vegetable are you most excited to see grown in Oman? (Artichokes, Asparagus, etc.).' },
                { date: '08-20', title: '"Made in Oman" Showcase', description: 'A weekly feature on a local food producer who uses locally-grown vegetables.' },
                { date: '08-24', title: 'Photo Album: "Architecture of Vegetable Storage"', description: 'The Architecture of Vegetable Storage in Oman.' },
                { date: '08-27', title: 'Shared Link: Research Paper', description: 'Post a link to a new research paper on vegetable seed genetics from a respected journal.' },
                { date: '08-31', title: '"Ask the Expert": Hydroponics Q&A', description: 'A thread with a Rakeeza representative answering questions about choosing vegetable seeds for hydroponics.' },
                { date: '09-03', title: 'Recipe Share: Traditional Omani Dish', description: 'Post a traditional Omani recipe that features a specific local vegetable.' },
                { date: '09-07', title: 'Corporate Spotlight: R&D Initiatives', description: 'A post highlighting the R&D initiatives of a company in developing better vegetable seeds.' },
                { date: '09-10', title: '"On This Day": Historical Event', description: 'A post about a key historical event in Oman\'s horticultural development.' },
                { date: '09-14', title: 'Call for Photos: #MyOmanGarden', description: 'Share your best photo of your home vegetable garden with the hashtag #MyOmanGarden.' },
                { date: '09-17', title: 'Video: Omani Vegetable Propagation', description: 'A natively uploaded YouTube documentary on Omani vegetable propagation.' },
                { date: '09-21', title: '"Behind the Brand": Artisanal Seed Co.', description: 'An interview with the founder of a local artisanal vegetable seed company.' },
                { date: '09-24', title: 'Holiday Greetings: Eid & National Day', description: 'Posts celebrating Eid and National Day with images of bountiful vegetable harvests.' },
                { date: '09-28', title: '"A Moment of Pride": Farm Award', description: 'Share news of an Omani vegetable farm winning an award for its sustainable practices.' },
                { date: '10-01', title: 'Volunteer Opportunity: Seed Bank', description: 'Post about opportunities to volunteer at a community vegetable seed bank.' },
                { date: '10-05', title: '"Did You Know?": Omani Melons', description: 'A post with interesting facts about the genetic diversity of Omani melons.' },
                { date: '10-08', title: 'Photo Album: "A Journey Through Oman\'s Vegetable Farms"', description: 'A photo album showing the diversity of farms.' },
                { date: '10-12', title: 'Live Q&A with a Chef', description: 'A local chef goes live to show how they select the best local vegetables.' },
                { date: '10-15', title: '"Our Community Heroes": Celebrating Farmers', description: 'A post celebrating local farmers who are preserving heirloom vegetable seeds.' }
            ],
            tiktokActiveDays: [0, 2, 4, 5],
            tiktokPosts: [
                { date: '07-20', title: 'Quick Tip: Heirloom Seeds', description: '3 Omani heirloom vegetable seeds you can grow at home.' },
                { date: '07-24', title: 'Trending Sound: Bird Protection', description: 'A humorous take on trying to keep birds away from your vegetable seedlings.' },
                { date: '07-27', title: 'Transition: Seed to Salad', description: 'From this (a handful of seeds) to THIS (a lush plate of salad).' },
                { date: '07-31', title: '"Made in Oman" Showcase', description: 'A rapid showcase of 5 products made from Omani-grown vegetables in 15 seconds.' },
                { date: '08-03', title: 'Quick History: The Falaj System', description: 'The Falaj system is an ancient aqueduct that waters our vegetable farms! #LearnOnTikTok' },
                { date: '08-07', title: 'POV: First Heirloom Tomato', description: 'You\'re trying a sweet Omani heirloom tomato for the first time.' },
                { date: '08-10', title: 'Cultural Etiquette: Market Selection', description: 'How to properly select vegetables at an Omani market.' },
                { date: '08-14', title: '"Things in Oman that just make sense"', description: 'Showcasing the aflaj, a modern greenhouse, and a vendor selling vegetable seeds.' },
                { date: '08-17', title: 'Dance in a Sunflower Field', description: 'A creator does a popular dance in a field of sunflowers grown for seed oil.' },
                { date: '08-21', title: '"Guess the Seed"', description: 'A close-up shot of a unique Omani vegetable seed.' },
                { date: '08-24', title: 'Quick Recipe: Tomato Salad', description: 'How to make the perfect tomato salad.' },
                { date: '08-28', title: '"A Day in My Life": Organic Farmer', description: 'A 60-second vlog showing planting vegetable seeds as an organic farmer in Oman.' },
                { date: '08-31', title: 'Satisfying Video: Gourd Cracking', description: 'The perfect cracking open of a dry gourd for its seeds.' },
                { date: '09-04', title: 'Rating Omani Vegetables', description: 'A fun video trying and rating different local vegetables.' },
                { date: '09-07', title: 'Come with me to a plant nursery', description: 'in Muscat.' },
                { date: '09-11', title: 'Quick Tour: Hydroponic Seedling Room', description: 'A 15-second tour of a hydroponic farm\'s seedling room.' },
                { date: '09-14', title: '"Unboxing": Heirloom Seeds', description: 'Opening a new packet of heirloom vegetable seeds.' },
                { date: '09-18', title: '"Did you know?": Cucumber Propagation', description: 'A quick fact about how cucumbers are propagated.' },
                { date: '09-21', title: '"Oman\'s Hidden Gems": Remote Farms', description: 'A rapid-fire montage of beautiful, remote vegetable farms.' },
                { date: '09-25', title: 'How it\'s made: Tomato Sauce', description: 'A quick video on making tomato sauce.' },
                { date: '09-28', title: 'AI-Generated Farm of the Future', description: 'I asked an AI to draw "Oman\'s Future Vegetable Farm".' },
                { date: '10-02', title: 'Best View in Oman', description: 'A video revealing a stunning viewpoint of terraced vegetable farms.' },
                { date: '10-05', title: 'Trying Omani Street Food', description: 'A video trying street food made with local vegetables.' },
                { date: '10-09', title: 'What\'s in my bag for planting?', description: 'A quick reveal of essential items for planting vegetables.' },
                { date: '10-12', title: 'My favorite building in Muscat', description: 'Showcasing a beautifully designed modern building.' },
                { date: '10-16', title: 'The sound of bees in a vegetable field', description: 'An immersive audio-visual clip.' }
            ],
            instagramActiveDays: [0, 1, 3, 4, 6],
            instagramPosts: [
                { date: '07-20', title: 'Reel: "Ancient Engineering, Modern Growth"', description: 'A drone shot flying through an aflaj channel that feeds into a field of lush green vegetables.' },
                { date: '07-23', title: 'Carousel: "The Colors of Oman\'s Harvest"', description: 'A photo series showcasing vibrant colors of heirloom tomatoes and peppers, with a slide about their seeds.' },
                { date: '07-27', title: 'Photo: "The Seed of Innovation"', description: 'A shot of a modern private research facility, captioned "Where Oman\'s future vegetable seeds are born."' },
                { date: '07-30', title: 'Reel: "From Seed to Salad in 30 Seconds"', description: 'A time-lapse of hydroponic lettuce growing.' },
                { date: '08-03', title: 'Story Poll: "Favorite Heirloom Vegetable?"', description: 'Which heirloom Omani vegetable is your favorite? (Options: Omani Melon, Local Cucumber, etc.).' },
                { date: '08-06', title: 'Influencer Takeover: Food Blogger', description: 'An Omani food blogger visits a farm, focusing on the unique heirloom vegetables they grow from saved seeds.' },
                { date: '08-10', title: 'Carousel: "The Art of Omani Vegetable Seed Pods"', description: 'A photo series of intricate, beautiful seed pods from native Omani plants.' },
                { date: '08-13', title: 'Reel: "The Tomato Harvest"', description: 'A satisfying, slow-motion video of heirloom tomatoes being picked.' },
                { date: '08-17', title: 'Quote Graphic: Hiba Al Husaini', description: 'A quote from Hiba Al Husaini on the importance of saving local vegetable seeds.' },
                { date: '08-20', title: 'Story Q&A: Agritech Researcher', description: 'With a researcher from a private agritech firm about their work in developing drought-tolerant vegetable seeds.' },
                { date: '08-24', title: 'Reel: "Respectful Innovation"', description: 'A split-screen Reel showing traditional terrace farming of vegetables on one side and a modern vertical farm on the other.' },
                { date: '08-27', title: 'Photo: "Omani Hospitality"', description: 'A staged photo of a meal featuring fresh, local vegetables.' },
                { date: '08-31', title: 'Infographic: "Water Savings"', description: 'A graphic comparing water usage for growing lettuce in hydroponics vs. traditional farming.' },
                { date: '09-03', title: 'Carousel: "The Faces of Omani Farming"', description: 'Portraits of farmers holding the vegetable seeds of their signature crop.' },
                { date: '09-07', title: 'Reel: "The Weaver\'s Hands"', description: 'A video of a weaver using dyes made from local vegetables.' },
                { date: '09-10', title: '"Guess the Seed"', description: 'A stunning macro photo of a unique vegetable seed.' },
                { date: '09-14', title: 'Reel: "The Making of Tomato Paste"', description: 'A cinematic look at the traditional process, starting with the harvest.' },
                { date: '09-17', title: 'Photo: "A Fort Guarding Farmland"', description: 'A majestic shot of a fort overlooking verdant vegetable farms.' },
                { date: '09-21', title: 'Carousel: "A Taste of the Souq"', description: 'Vibrant photos of vegetables and seeds at a local market.' },
                { date: '09-24', title: 'Reel: "Dhows at Dawn"', description: 'A video of traditional boats, connecting to Oman\'s history of trading vegetable seeds.' },
                { date: '09-28', title: 'Story Quiz: "Omani Heirloom Vegetables"', description: 'How much do you know about Omani heirloom vegetables?' },
                { date: '10-01', title: 'Photo: "The Lone Gourd Vine"', description: 'An artistic shot of a gourd vine growing on a cliff edge.' },
                { date: '10-05', title: 'Reel: "The Perfect Drizzle"', description: 'A slow-motion video of olive oil being drizzled on a fresh salad.' },
                { date: '10-08', title: 'Carousel: "Modern Muscat\'s Green Lungs"', description: 'Showcasing rooftop vegetable gardens.' },
                { date: '10-12', title: 'User-Generated Content: #OmanGrows', description: 'Feature a photo from a home gardener showing their thriving vegetable plants grown from local seeds.' },
                { date: '10-15', title: 'Reel: "The Calligrapher\'s Ink"', description: 'A video of calligraphy being written using ink made from vegetable dyes.' }
            ],
            linkedinActiveDays: [0, 2, 4],
            linkedinPosts: [
                { date: '07-22', title: 'Article: "Oman\'s Vision: Driving Economic Diversification"', description: 'How Vegetable Seed Technology is Driving Economic Diversification.' },
                { date: '07-24', title: 'Infographic: "Oman\'s Food Security Goals"', description: 'The Role of Improved Vegetable Seed Varieties.' },
                { date: '07-29', title: 'Leadership Insights: CEO Quote', description: 'A quote from the CEO of an agricultural company on investing in local vegetable seed R&D.' },
                { date: '07-31', title: 'Company Profile: Rakeeza Smart Agriculture', description: 'A detailed look at Rakeeza Smart Agriculture and its vegetable seed selection strategy.' },
                { date: '08-05', title: 'Investment Brief: "Top 5 Reasons to Invest"', description: 'The Top 5 Reasons to Invest in Oman\'s Vegetable Seed Technology Sector.' },
                { date: '08-07', title: 'Case Study: University-Industry Partnerships', description: 'How University-Industry Partnerships Commercialize New Vegetable Seed Varieties.' },
                { date: '08-12', title: 'Workforce Analysis: "Omanization in Agritech"', description: 'Building Skills in Horticulture and Plant Genetics.' },
                { date: '08-14', title: 'Project Update: "Al Jabal Al Akhdar Tomato Project"', description: 'A Model for High-Value Vegetable Cultivation.' },
                { date: '08-19', title: 'Thought Leadership: Public-Private Partnerships', description: 'An article by an industry expert on "Public-Private Partnerships: The Key to a Modern Omani Vegetable Seed Sector."' },
                { date: '08-21', title: 'Data Deep Dive: Economic Impact of Tomato Yields', description: 'An analysis of the economic impact of improved tomato seed yields on food import bills.' },
                { date: '08-26', title: '"Meet the Leader": CEO Interview', description: 'A professional bio and interview with a prominent Omani CEO in the vegetable seed industry.' },
                { date: '08-28', title: 'White Paper: Foreign Investment Framework', description: 'The Legal Framework for Foreign Investment in Omani Horticulture.' },
                { date: '09-02', title: 'Webinar Announcement: "Sustainable Seed Sourcing"', description: 'Join our webinar on "Sustainable Vegetable Seed Sourcing in Arid Climates: Lessons from Oman."' },
                { date: '09-04', title: 'Industry News: Greenhouse Investment', description: 'Major Food Distributor Announces New Investment in Local Greenhouse Tomato Production.' },
                { date: '09-16', title: 'Company Milestone: Lettuce Seed Trials', description: 'Rakeeza Smart Agriculture Celebrates Successful Trials of 5 New Lettuce Seed Varieties.' },
                { date: '09-18', title: 'Networking Post: International Partners', description: 'We\'re looking to connect with international vegetable seed technology partners.' },
                { date: '09-23', title: 'Analysis: India-Oman DTAA Impact', description: 'The Impact of the India-Oman DTAA on Vegetable and Seed Trade.' },
                { date: '09-25', title: '"The Role of Higher Education"', description: 'How universities are shaping the next generation of horticulturists.' },
                { date: '09-30', title: 'Sustainability Report Summary', description: 'A post summarizing a company\'s report, focusing on vegetable seed biodiversity initiatives.' },
                { date: '10-02', title: '"A Model for the GCC"', description: 'An article arguing why Oman\'s approach to heirloom vegetable seed preservation is a model for the region.' },
                { date: '10-07', title: 'Job Posting: Head of Horticulture', description: 'We\'re hiring a Head of Horticulture with expertise in arid climate seed selection.' },
                { date: '10-09', title: '"The Circular Economy in Oman"', description: 'Exploring how agricultural waste is being repurposed to fertilize vegetable gardens.' },
                { date: '10-14', title: '"From the Ground Up": Startup Profiles', description: 'A series profiling successful Omani startups in the vegetable seed tech space.' },
                { date: '10-16', title: '"Digital Transformation of Omani Farms"', description: 'How IoT is being used to monitor vegetable seedling health.' }
            ],
            youtubeActiveDays: [0, 3, 5, 6],
            youtubePosts: [
                { date: '07-20', title: 'Documentary: "The Veins of the Mountain"', description: 'A film about the aflaj irrigation systems, focusing on the heirloom vegetable seeds and crops they sustain.' },
                { date: '07-25', title: 'Series: "Oman\'s Vision: Sowing the Future"', description: 'Interviews with CEOs of leading agritech companies about the national strategy for food security, highlighting investments in vegetable seed technology.' },
                { date: '07-27', title: 'Explainer: "Hydroponics in the Desert"', description: 'An animated video explaining how hydroponics works, showcasing specific lettuce and tomato seed varieties that thrive in these systems.' },
                { date: '08-01', title: 'Travel Vlog: "Jabal Al Akhdar\'s Harvest"', description: 'A travel influencer explores the "Green Mountain," tasting heirloom tomatoes and visiting terraced vegetable farms.' },
                { date: '08-03', title: 'Business Profile: "Inside Rakeeza Smart Agriculture"', description: 'A tour of a modern hydroponics farm, interviewing founders about their vegetable seed selection process.' },
                { date: '08-08', title: 'Cooking Show: "Modern Omani Table"', description: 'A chef creates fusion dishes using traditional Omani vegetables and new hydroponic greens.' },
                { date: '08-10', title: 'Historical Deep Dive: "The Spice Trail"', description: 'A documentary tracing ancient trade routes, discussing the historical trade of vegetable seeds and spices.' },
                { date: '08-15', title: 'University Spotlight: "Innovations from Leading Researchers"', description: 'Featuring researchers discussing their work on developing climate-resilient seeds for Omani cucumbers and peppers.' },
                { date: '08-17', title: 'Tutorial: "Your First Home Hydroponics Kit for Herbs"', description: 'A step-by-step guide for setting up a small, home-based hydroponic system for herbs, including choosing the right seeds.' },
                { date: '08-22', title: 'Agritourism Feature: "Tomato Picking in the Mountains"', description: 'A family-friendly video showcasing the unique experience of picking rare tomato varieties.' },
                { date: '08-24', title: 'Drone Showcase: "Oman: From Desert to Oasis"', description: 'A cinematic drone video contrasting desert landscapes with the lush green of oases, highlighting the vegetable gardens.' },
                { date: '08-29', title: 'CEO Interview: Food Importer', description: 'An in-depth conversation with the CEO of a major food importer about their strategy to source more vegetables locally.' },
                { date: '08-31', title: 'Explainer: "Digital Twin for a Tomato Seed?"', description: 'An animated video explaining how tech is used to model how different vegetable seed varieties will perform.' },
                { date: '09-05', title: 'Series: "Guardians of the Gourd"', description: 'A documentary-style series following a farmer dedicated to preserving ancient Omani gourd and squash varieties.' },
                { date: '09-07', title: '"Made in Oman" Series', description: 'A series profiling high-quality Omani vegetable products, starting with the seeds they come from.' },
                { date: '09-12', title: 'Debate: "Heirloom vs. Hybrid"', description: 'A discussion between a traditional farmer and an agritech seed specialist on finding the right vegetable seed for Oman.' },
                { date: '09-14', title: 'Architectural Tour: Farming Villages', description: 'Exploring unique farming villages, focusing on traditional structures used for storing vegetable seeds.' },
                { date: '09-19', title: '"The Science of Soil"', description: 'A professor explains the unique soil of Omani terraces and which heirloom vegetable seeds are perfectly adapted to it.' },
                { date: '09-21', title: 'Investment Guide: "Why Invest in Oman\'s Seed Tech?"', description: 'A video aimed at international investors about vegetable seed technology.' },
                { date: '09-26', title: 'Day in the Life: Hiba Al Husaini, Organic Farmer', description: 'Following the young organic farming advocate, with a focus on her vegetable seed saving and planting practices.' },
                { date: '09-28', title: '"The Story of the Omani Lime"', description: 'A cultural and historical look at the importance of the lime in Omani life, including its propagation.' },
                { date: '10-03', title: 'Behind the Scenes: "A Five-Star Salad\'s Seeds"', description: 'Tracing ingredients for a luxury hotel\'s salad back to the specific vegetable seed varieties chosen.' },
                { date: '10-05', title: 'Water Management Masterclass', description: 'An expert explains how water strategy influences which vegetable crop seeds are promoted.' },
                { date: '10-10', title: '"From Netherlands to Oman"', description: 'The story of how a Dutch vegetable seed company\'s varieties are thriving in Omani greenhouses.' },
                { date: '10-12', title: '"The Future of Greens"', description: 'Exploring research into high-nutrition leafy greens and the development of seeds adapted for Oman.' },
                { date: '10-17', title: '"Secrets of the Sea"', description: 'A documentary on Oman\'s aquaculture, including using fish waste to fertilize coastal vegetable gardens.' }
            ],
            whatsappActiveDays: [1, 3, 5],
            whatsappPosts: [
                { date: '07-19', title: "WhatsApp: Good morning, farmers! ☀️", description: "When we see this bountiful harvest, we know your hard work has paid off. Fertile land brings prosperity to all. Congratulations! (Image of a bountiful harvest)" },
                { date: '08-02', title: "WhatsApp: Our children deserve the best, and good land provides it. 🌱", description: "Their health starts in our green fields. (Short video of a child eating fresh fruit, then a green field)" }
            ]
        }
    },
    uganda: {
        name: "Uganda",
        landscape: {
            penetration: "24.6%",
            socialUsers: "11.77 Million",
            keyInsight: "Twitter Leads & Youthful Audience",
            platforms: {
                labels: ['Twitter', 'Facebook', 'Pinterest', 'YouTube', 'Instagram', 'LinkedIn', 'TikTok', 'WhatsApp'],
                data: [35.74, 20.11, 19.8, 12.17, 8.32, 1.88, 0.9, 0.7],
                colors: ['#1DA1F2', '#4267B2', '#E60023', '#FF0000', '#C13584', '#0A66C2', '#000000', '#25D366']
            }
        },
        behavior: {
            peakTimes: [
                { time: "Morning (9 AM - 11 AM)", platforms: "Twitter, Facebook", icon: "SunIcon" },
                { time: "Midday", platforms: "LinkedIn", icon: "BuildingOfficeIcon" },
                { time: "Evening (7 PM - 10 PM)", platforms: "YouTube, TikTok", icon: "MoonIcon" }
            ],
            engagingContent: [
                { nameKey: "videoContent", icon: "VideoCameraIcon" },
                { nameKey: "influencerMarketing", icon: "StarIcon" },
                { nameKey: "liveStreaming", icon: "SignalIcon" },
                { nameKey: "interactiveContent", icon: "QuestionMarkCircleIcon" },
                { nameKey: "storytelling", icon: "BookOpenIcon" },
                { nameKey: "educationalContent", icon: "AcademicCapIcon" }
            ]
        },
        agriculture: {
            topics: [
                { titleKey: "smartAgriculture", descriptionKey: "smartAgricultureDesc" },
                { titleKey: "knowledgeExchange_ug", descriptionKey: "knowledgeExchangeDesc_ug" },
                { titleKey: "marketAccess_ug", descriptionKey: "marketAccessDesc_ug" }
            ],
            platforms: [
                { name: "WhatsApp", descriptionKey: "whatsappDesc_ug", icon: "ChatBubbleLeftRightIcon" },
                { name: "Facebook / YouTube", descriptionKey: "facebookYoutubeDesc_ug", icon: "PlayCircleIcon" }
            ]
        },
        calendar: {
            activeDays: [0, 1, 2, 3, 4, 5, 6],
            activePeriods: {
                0: ['7 PM - 10 PM'], 1: ['9 AM - 11 AM', '7 PM - 10 PM'], 2: ['9 AM - 11 AM', '7 PM - 10 PM'], 3: ['9 AM - 12 PM', '7 PM - 10 PM'], 4: ['9 AM - 11 AM', '7 PM - 10 PM'], 5: ['8 PM (Instagram)', '6 AM - 9 AM', '7 PM - 10 PM'], 6: ['7 PM - 10 PM']
            },
            facebookActiveDays: [2, 5],
            facebookPosts: [
                { date: '07-22', title: 'Live Debate: Hybrid Seeds', description: 'Should Ugandan farmers embrace hybrid vegetable seeds? A conversation for farmers.' },
                { date: '07-25', title: 'Poll: Biggest Seed Challenge', description: 'What is the biggest challenge when buying vegetable seeds? (Access, Cost, Quality/Fakes, Information).' },
                { date: '07-29', title: 'UGC Campaign: #UgandaGrows', description: 'Share a photo of your best vegetable harvest with #UgandaGrows. We\'ll feature the best ones!' },
                { date: '08-01', title: 'Positive News Share', description: 'Share an article about a community that has increased its nutrition by planting diverse vegetables.' },
                { date: '08-05', title: 'Group Promotion: Farmers Network', description: 'Create and promote a Facebook Group called "Ugandan Vegetable Farmers & Innovators Network."' },
                { date: '08-08', title: 'Photo Album: Agricultural Show', description: 'A comprehensive album with photos from the National Agricultural Show\'s Vegetable Seed Pavilion.' },
                { date: '08-12', title: 'Link Share: Counterfeit Crackdown', description: 'An article from The Monitor about a local business cracking down on counterfeit vegetable seed dealers.' },
                { date: '08-15', title: 'Meet the Innovator', description: 'A long-form post profiling a young entrepreneur who developed a new vegetable seed coating.' },
                { date: '08-19', title: 'Event Creation: Virtual Farmer Field Day', description: 'A Facebook Event for a virtual "Farmer Field Day" showcasing new vegetable seed varieties.' },
                { date: '08-22', title: 'Ask Me Anything: Seed Company Owner', description: 'A text-based AMA thread with a successful vegetable seed company owner.' },
                { date: '08-26', title: 'Video Share: Innovator Profile', description: 'Natively upload a YouTube video profiling a Ugandan vegetable seed innovator for better reach.' },
                { date: '08-29', title: 'Discussion Starter: Advice for Youth', description: 'What one piece of advice would you give to a young person starting a vegetable farm about choosing seeds?' },
                { date: '09-02', title: 'Success Story: Certified Seeds', description: 'A detailed post about a farmer group that doubled their income after switching to certified vegetable seeds.' },
                { date: '09-05', title: 'Resource Hub: Pinned Post', description: 'A pinned post with links to certified vegetable seed dealers and business development services.' },
                { date: '09-09', title: 'Fact vs. Fiction: Seed Myths', description: 'A post debunking common myths about vegetable seeds.' },
                { date: '09-12', title: 'Our Partners in Progress', description: 'A post thanking a local tech company for their work in improving the vegetable seed sector.' },
                { date: '09-16', title: 'A Look Inside a Seed Lab', description: 'A photo tour of a private vegetable breeding lab.' },
                { date: '09-19', title: 'Job Board', description: 'A weekly thread for sharing job opportunities at vegetable seed companies and research institutions.' },
                { date: '09-23', title: 'From the Diaspora', description: 'Share a message of encouragement from a successful Ugandan horticulturist living abroad.' },
                { date: '09-26', title: 'Celebrate Our Culture', description: 'A post explaining the cultural significance of vegetable sharing ceremonies.' },
                { date: '09-30', title: 'Digital Skills Workshop', description: 'A post promoting a free online workshop on using your phone to verify vegetable seed quality.' },
                { date: '10-03', title: 'The Marketplace', description: 'A dedicated group where certified vegetable seed dealers can post their available stock.' },
                { date: '10-07', title: 'Local Hero Spotlight', description: 'A feature on an agricultural extension officer who has helped their community adopt better vegetable seeds.' },
                { date: '10-10', title: 'The Power of Mobile Money', description: 'A post explaining how mobile money has made it easier for farmers to buy quality vegetable seeds.' },
                { date: '10-14', title: 'A Greener Uganda', description: 'Highlighting efforts to promote indigenous vegetable planting.' },
                { date: '10-17', title: 'The Reading List', description: 'A post recommending manuals and guides on vegetable seed production.' }
            ],
            tiktokActiveDays: [3, 6],
            tiktokPosts: [
                { date: '07-23', title: 'Dance Challenge: #VegetableDance', description: 'Create a #VegetableDance challenge using a hit song by a Ugandan artist.' },
                { date: '07-26', title: 'Comedy Skit: Fake Seeds', description: 'A Ugandan comedian acts out a "Trying to sell fake tomato seeds to my grandma" skit.' },
                { date: '07-30', title: 'Tour Guide for a Day', description: 'I\'m showing you a cabbage nursery in 60 seconds! GO!' },
                { date: '08-02', title: 'Trending Sound: Seed Prices', description: 'A farmer lip-syncs a funny line about the price of vegetable seeds.' },
                { date: '08-06', title: 'How to spot FAKE vegetable seeds', description: 'A humorous but educational guide.' },
                { date: '08-09', title: 'POV: A seedling when it rains', description: 'You\'re a tomato seedling and the rain finally comes.' },
                { date: '08-13', title: 'Quick How-To: Planting a cabbage seed', description: 'How to plant a cabbage seed in 15 seconds.' },
                { date: '08-16', title: 'Things in Uganda that just make sense', description: 'Showing a rolex stand, a boda-boda loaded with cabbage, and a farmer using a smartphone.' },
                { date: '08-20', title: 'Rating Ugandan Greens', description: 'A fast-paced review of dodo, nakati, and buga.' },
                { date: '08-23', title: 'Come with me to a seed shop', description: 'in Kasese.' },
                { date: '08-27', title: 'I asked my grandpa...', description: 'what vegetables they grew in the 60s.' },
                { date: '08-30', title: 'This is not just a tomato...', description: 'it\'s a high-yield, disease-resistant tomato. A classic Ugandan ag-joke.' },
                { date: '09-03', title: 'My innovator story', description: 'A 60-second pitch for a new vegetable seed-planting robot.' },
                { date: '09-06', title: 'The biggest lie about farming is...', description: 'that you can plant any vegetable seed anywhere. A stitchable video.' },
                { date: '09-10', title: '"Unboxing" an Agri-Tech Gadget', description: 'Opening a new soil testing kit for my vegetable garden.' },
                { date: '09-13', title: 'If Ugandan vegetables had theme songs', description: 'Playing different tunes for tomatoes, cabbage, and matoke.' },
                { date: '09-17', title: 'My farm\'s morning routine', description: 'checking the vegetable seedlings.' },
                { date: '09-20', title: 'Trying to pronounce Latin name', description: 'for tomato (Solanum lycopersicum).' },
                { date: '09-24', title: 'This solar panel powers our nursery', description: 'A quick showcase of a solar-powered vegetable seedling nursery.' },
                { date: '09-27', title: 'The ultimate Ugandan food combo', description: 'starts with this vegetable...' },
                { date: '10-01', title: 'POV: You\'re a fish in Lake Victoria', description: 'seeing a vegetable garden on the shore.' },
                { date: '10-04', title: 'My top 3 Afrobeats songs to plant to', description: 'A fun, music-based video for planting vegetables.' },
                { date: '10-08', title: 'How to make a mini-greenhouse', description: 'for vegetable seedlings in 30 seconds.' },
                { date: '10-11', title: 'This is what 5,000 Shillings gets you', description: 'in vegetable seeds.' },
                { date: '10-15', title: 'The craziest thing I\'ve seen on a boda', description: 'a whole nursery of tomato seedlings.' },
                { date: '10-18', title: 'My pitch for the next innovation challenge', description: 'A vegetable seed-sorting machine.' }
            ],
            instagramActiveDays: [1, 4],
            instagramPosts: [
                { date: '07-21', title: 'Reel: "The Gorilla Grin"', description: 'A video of a gorilla, captioned "Protecting their home protects the wild relatives of our vegetables."' },
                { date: '07-24', title: 'Carousel: "Colors of Kampala\'s Market"', description: 'A photo series capturing vibrant fabrics, foods, and a close-up of different types of vegetable seeds for sale.' },
                { date: '07-28', title: 'Photo: "Rwenzori Sunrise"', description: 'A stunning landscape shot overlooking fields of vegetables.' },
                { date: '07-31', title: 'Reel: "From Tomato to Sauce"', description: 'A fast-paced, satisfying video of tomatoes being processed.' },
                { date: '08-04', title: 'Story Poll: "Most important vegetable?"', description: 'What\'s the most important vegetable in Uganda? (Tomato, Cabbage, Onion, Dodo/Amaranth).' },
                { date: '08-07', title: 'Influencer Collaboration: Comedian', description: 'Partner with a Ugandan comedian for a funny Reel about accidentally planting fake vegetable seeds.' },
                { date: '08-11', title: 'Carousel: "Kampala Fashion Week"', description: 'Highlights focusing on designers who use natural dyes from vegetables.' },
                { date: '08-14', title: 'Reel: "The Perfect Vegetable Seedbed"', description: 'A quick, mesmerizing tutorial on how to prepare a seedbed.' },
                { date: '08-18', title: 'Quote Graphic: Young Innovator', description: 'An inspiring quote from a young innovator about solving food insecurity through better vegetable seeds.' },
                { date: '08-21', title: 'Story Q&A: Seed Startup', description: 'With a young entrepreneur who has successfully received funding for their vegetable seed-coating startup.' },
                { date: '08-25', title: 'Reel: "Aspirational Pragmatism"', description: 'A split-screen showing a young person dreaming, then using an app to identify a quality vegetable seed.' },
                { date: '08-28', title: 'Photo: "The Source of the Nile"', description: 'A beautiful photo from Jinja, captioned "Where life-giving water begins its journey to our vegetable farms."' },
                { date: '09-01', title: 'Infographic: "Uganda\'s Digital Boom"', description: 'A graphic showing how social media growth is helping vegetable farmers connect.' },
                { date: '09-04', title: 'Carousel: "The Faces of Innovation"', description: 'Portraits of innovation challenge finalists holding their vegetable seed-related inventions.' },
                { date: '09-08', title: 'Reel: "Boda-Boda Ballet"', description: 'An artistic video capturing Kampala\'s traffic, focusing on the bags of vegetable seeds being transported.' },
                { date: '09-11', title: '"Guess the Seedling"', description: 'A close-up photo of a tropical Ugandan vegetable sprouting.' },
                { date: '09-15', title: 'Reel: "The Rhythm of the Harvest"', description: 'A video of farmers harvesting cabbages, set to an infectious Afrobeats song.' },
                { date: '09-18', title: 'Photo: "A Student\'s Dream"', description: 'A portrait of a university student studying horticulture at a leading university.' },
                { date: '09-22', title: 'Carousel: "The Art of Natural Dyes"', description: 'A photo story on making dyes from vegetables.' },
                { date: '09-25', title: 'Reel: "Planting with a Purpose"', description: 'A first-person view of planting vegetable seeds with a modern hand-planter.' },
                { date: '09-29', title: 'Story Quiz: "Ugandan Eggplant Varieties"', description: 'How much do you know about Ugandan eggplant varieties?' },
                { date: '10-02', title: 'Photo: "The Shoebill Stork"', description: 'A photo of this iconic bird in a wetland near vegetable farms.' },
                { date: '10-06', title: 'Reel: "The Power of a Solar Panel"', description: 'A quick video showing a solar panel powering a vegetable seed dryer.' },
                { date: '10-09', title: 'Carousel: "Street Art of Kampala"', description: 'Showcasing vibrant murals with vegetable and farming themes.' },
                { date: '10-13', title: 'User-Generated Content: #UgandaHarvest', description: 'Feature a photo from a follower showing their successful tomato harvest.' },
                { date: '10-16', title: 'Reel: "The Dance-Off"', description: 'A fun video of young farmers having a dance battle in a newly planted vegetable field.' }
            ],
            linkedinActiveDays: [2, 4],
            linkedinPosts: [
                { date: '07-22', title: 'Startup Profile: "Startup of the Week"', description: 'Profiling a Ugandan company that developed a new vegetable seed coating technology.' },
                { date: '07-24', title: 'Investment Analysis: "Why VC is Turning to Uganda"', description: 'Why Venture Capital is Turning its Eyes to Uganda\'s Vegetable Seed Sector.' },
                { date: '07-29', title: 'Article: "Beyond Subsistence"', description: 'How Private Sector Innovation is Driving Vegetable Commercialization in Uganda.' },
                { date: '07-31', title: 'Ecosystem Spotlight: "A Deep Dive into Agritech"', description: 'The Role of Hubs in Fostering Vegetable Seed Innovation.' },
                { date: '08-05', title: 'Leadership Insight: UFAAS Head', description: 'An article by the head of a private extension service on delivering better vegetable seed information.' },
                { date: '08-07', title: 'Case Study: "Innovation Challenges"', description: 'Creating a Pipeline of Bankable Vegetable-Tech Startups.' },
                { date: '08-12', title: 'Infographic: "Economic Impact of Counterfeit Seeds"', description: 'Based on private sector data.' },
                { date: '08-14', title: 'Meet the Founder: Seed Company', description: 'A professional profile and interview with a successful Ugandan vegetable seed company founder.' },
                { date: '08-19', title: 'Agribusiness Deep Dive: "The Ugandan Chili Value Chain"', description: 'Opportunities for Investment in High-Quality Seedlings.' },
                { date: '08-21', title: 'Company News: "Local Seed Co. Expansion"', description: 'Local Seed Company Announces Phase 2 Expansion of its Hybrid Tomato Seed Production.' },
                { date: '08-26', title: 'Thought Leadership: "Digital Transformation"', description: 'Digital Transformation of the Vegetable Seed Sector is a Necessity for Ugandan Agribusiness.' },
                { date: '08-28', title: 'Project Showcase: "Private Seed Tracking System"', description: 'A Fight Against Counterfeits Using Mobile Tech.' },
                { date: '09-02', title: 'The Talent Pipeline: Makerere University', description: 'How Makerere University\'s Horticulture Program is preparing graduates for the modern seed industry.' },
                { date: '09-04', title: 'Policy Analysis: "Impact of National Seed Policy"', description: 'On Rural Entrepreneurship and Vegetable Agro-Input Shops.' },
                { date: '09-09', title: 'The Rise of the Digital Farmer', description: 'An article on the success of private platforms in connecting farmers to certified vegetable seed.' },
                { date: '09-11', title: 'Webinar Announcement: "De-risking Agricultural Loans"', description: 'Join our webinar on "De-risking Agricultural Loans: The Role of Quality Vegetable Seeds."' },
                { date: '09-16', title: 'A New Class of Leader', description: 'Profiling innovation challenge winners whose inventions are related to vegetable seeds.' },
                { date: '09-18', title: 'Market Report: "Export Opportunities for Ugandan Vegetables"', description: 'Opportunities for Ugandan-Grown Hot Peppers and Eggplants.' },
                { date: '09-23', title: 'The Gender Dividend', description: 'An article on the ROI of investing in women-led vegetable seed companies.' },
                { date: '09-25', title: 'From Kampala to the World', description: 'The story of a Ugandan startup that has successfully exported its vegetable seed technology.' },
                { date: '09-30', title: 'Job Posting: Head of R&D', description: 'Seeking: Head of R&D for a fast-growing vegetable seed company in Kampala.' },
                { date: '10-02', title: 'The Legal Landscape: PVP Rights', description: 'A guide to Plant Variety Protection (PVP) rights for vegetable breeders in Uganda.' },
                { date: '10-07', title: 'The Power of Partnerships', description: 'Highlighting a successful collaboration between a bank and a vegetable seed company to offer input financing.' },
                { date: '10-09', title: 'Data-Driven Decisions', description: 'How Ugandan vegetable seed companies are using data from field trials to guide their breeding programs.' },
                { date: '10-14', title: 'The Future of Logistics', description: 'How tech is solving last-mile delivery challenges for getting vegetable seeds to farmers.' },
                { date: '10-16', title: 'A Conversation with a VC', description: 'An interview with a venture capitalist on what they look for in a Ugandan agritech startup.' }
            ],
            youtubeActiveDays: [1, 5],
            youtubePosts: [
                { date: '07-21', title: 'Series: "Ugandan Innovators"', description: 'A weekly show profiling young agritech entrepreneurs focusing on their vegetable seed-related innovations.' },
                { date: '07-25', title: 'Vlog: "A Day in Nakasero Market"', description: 'A fast-paced vlog exploring the city\'s main vegetable market, talking to vendors about popular vegetables.' },
                { date: '07-28', title: 'Wildlife Doc: "The Gorillas of Bwindi"', description: 'A film with a segment on the importance of preserving the natural habitat which is home to wild relatives of our vegetable crops.' },
                { date: '08-01', title: 'Tutorial: "ICT4Farmers App"', description: 'A tutorial on how to use a popular farming app to find certified vegetable seed dealers.' },
                { date: '08-04', title: 'Success Story: "From One Seed Packet to CEO"', description: 'An inspiring documentary on a farmer who built a commercial enterprise from one packet of improved tomato seeds.' },
                { date: '08-08', title: 'Event Coverage: "Jinja Agricultural Show"', description: 'An energetic montage of the best new vegetable seed varieties.' },
                { date: '08-11', title: 'Training Series: "Sauce for Success"', description: 'A series on vegetable value-addition, such as making tomato sauce and chili paste.' },
                { date: '08-15', title: 'Profile: "Meet an AYuTe Winner"', description: 'An in-depth interview with a winner whose innovation helps vegetable farmers.' },
                { date: '08-18', title: 'Travel Guide: "Farms of the Nile"', description: 'An adventure-focused video showcasing unique vegetable farms along the Nile.' },
                { date: '08-22', title: 'Explainer: "Climate-Smart Vegetable Seed"', description: 'An animated video explaining concepts like drought-resistant tomatoes in a Ugandan context.' },
                { date: '08-25', title: 'Farm Tour: Seed Multiplication Farm', description: 'A virtual tour of a successful seed multiplication farm for vegetables like cabbage or carrots.' },
                { date: '08-29', title: '"Ask an Agronomist" Q&A Series', description: 'A Q&A series where scientists from a private research firm answer farmer questions about new vegetable seed varieties.' },
                { date: '09-01', title: 'DIY Build: "Low-Cost Hand Planter"', description: 'How to Build a Low-Cost Hand Planter for Vegetable Seeds.' },
                { date: '09-05', title: 'Series: "The Business of Vegetables"', description: 'A series on financial literacy, focusing on calculating the ROI of buying certified vegetable seeds.' },
                { date: '09-08', title: '"Uganda\'s Hidden Gems"', description: 'A travel series exploring lesser-known agricultural regions and the unique vegetables they cultivate.' },
                { date: '09-12', title: 'Debate: Hybrids vs. Open-Pollinated', description: 'Which Vegetable Seed is Best for Business?' },
                { date: '09-15', title: '"The Boda-Boda Vegetable Delivery"', description: 'A look at the vital role of motorcycle taxis in the last-mile delivery of vegetable seeds.' },
                { date: '09-19', title: '"The Chili Story"', description: 'From seed to hot sauce, a documentary on the journey of Ugandan chili.' },
                { date: '09-22', title: '"Meet the Digital Farmers"', description: 'Profiling farmers who are successfully using mobile apps to identify counterfeit vegetable seeds.' },
                { date: '09-26', title: '"The Fight Against Counterfeit Seeds"', description: 'A feature on how local businesses are using tech to ensure seed quality.' },
                { date: '09-29', title: '"Women in Agribusiness"', description: 'A series of interviews with successful female entrepreneurs who run vegetable seed shops.' },
                { date: '10-03', title: '"The Art of Value Addition"', description: 'Showcasing how communities are processing tomatoes and peppers into higher-value products.' },
                { date: '10-06', title: '"Kampala\'s Startup Scene"', description: 'A look at the tech hubs supporting young entrepreneurs developing solutions for the vegetable seed sector.' },
                { date: '10-10', title: '"The Music of the Harvest"', description: 'A collaboration with a popular Ugandan musician to create a music video filmed during a vegetable harvest.' },
                { date: '10-13', title: '"A Tale of Two Farmers"', description: 'A video comparing a farmer using fake vegetable seeds with one using certified seeds.' },
                { date: '10-17', title: '"The Rolex Challenge"', description: 'A fun video where a host tries to find the best rolex, with a segment on the tomatoes and onions used.' }
            ],
            whatsappActiveDays: [1, 4],
            whatsappPosts: [
                { date: '07-26', title: "WhatsApp: Seeing your farms flourish fills us with joy! ✨", description: "Your hard work is creating abundance and a better life for everyone. Keep up the great work! (Voice note from a SeedTech representative)" },
                { date: '08-09', title: "WhatsApp: The satisfaction of a thriving harvest is truly unmatched! 👏", description: "Your dedication to the land is building a prosperous future. We are proud of your achievements! (Image of a farmer proudly displaying their produce)" }
            ]
        }
    }
};

export const translations: Translations = {
    en: {
        mainTitle: "Social Media Analysis and Content Calendar for Seedtech",
        mainSubtitle: "Explore the digital landscape in Sudan, Oman, and Uganda",
        sudan: "Sudan",
        oman: "Oman",
        uganda: "Uganda",
        all: "All",
        sectionTitleLandscape: "Digital Landscape Overview",
        landscapeIntro_sudan: "Sudan's digital landscape is characterized by the near-total dominance of Facebook, supported by its 'Free Mode' feature, making it a lifeline for information. Mobile access is the primary norm, guiding content strategies towards simplicity and accessibility.",
        landscapeIntro_oman: "Oman features a mature digital environment with high internet penetration. Users are spread across several major platforms, with a clear preference for high-quality visual content and content that reflects local culture.",
        landscapeIntro_uganda: "Uganda's digital landscape is diverse and largely youth-driven. TikTok is the leading platform for engagement. The tone should be empowering, pragmatic, and aspirational, celebrating accessible innovation and the journey from subsistence farming to commercial vegetable enterprise.",
        statTitleInternet: "Internet Penetration",
        statTitleSocial: "Social Media Users",
        statTitleInsight: "Key Insight",
        chartTitle: "Platform Market Share Distribution",
        marketShareText_sudan: "Facebook holds an overwhelming market share of nearly 90%, making it the primary channel for digital communication. Twitter comes in a distant second, followed by YouTube, Instagram, Pinterest, and LinkedIn with much smaller shares.",
        marketShareText_oman: "Facebook leads the market but with less dominance, with a very strong presence from Twitter and Instagram, followed by Pinterest, YouTube, and LinkedIn. This diversity requires a multi-platform strategy to reach different audience segments.",
        marketShareText_uganda: "Twitter tops the market share, followed by Facebook and Pinterest, then YouTube, Instagram, and LinkedIn. This diversity reflects the preferences of a young, digitally active audience, making it a dynamic market for digital marketing.",
        sectionTitleBehavior: "User Behavior & Engagement Patterns",
        behaviorIntro: "Here, we explore when users are most active and which content types generate the highest engagement. Understanding these patterns is key to effectively communicating with the local audience.",
        peakTimesTitle: "Peak Activity Times (Estimated)",
        engagingContentTitle: "Most Engaging Content",
        visualContent: "Visual Content",
        breakingNews: "Breaking News",
        politicalDiscourse: "Political Discourse",
        humorSatire: "Humor & Satire",
        localContent: "Local Content",
        personalStories: "Personal Stories",
        visualStorytelling: "Visual Storytelling",
        shortFormVideo: "Short-form Video",
        influencerMarketing: "Influencer Marketing",
        thoughtLeadership: "Thought Leadership",
        directEngagement: "Direct Engagement",
        videoContent: "Video Content",
        liveStreaming: "Live Streaming",
        interactiveContent: "Interactive Content",
        storytelling: "Storytelling",
        educationalContent: "Educational Content",
        sectionTitleAgri: "Agriculture in the Digital Age",
        agriIntro_sudan: "In Sudan, social media is used as a vital tool for agricultural extension and market access, especially amid the challenges posed by conflict. Platforms facilitate knowledge exchange on resilient farming techniques.",
        agriIntro_oman: "In Oman, digital agricultural content focuses on addressing environmental challenges like water scarcity. There is significant interest in technological innovations such as protected agriculture and smart irrigation to enhance food security.",
        agriIntro_uganda: "In Uganda, the digital agricultural dialogue revolves around using technology to address climate threats. There is a strong focus on digitization and financial inclusion programs to empower farmers in rural areas.",
        agriTopicsTitle: "Top Agricultural Topics",
        agriTopicsSubtitle: "Click on a topic to explore more details.",
        knowledgeDissemination: "Knowledge Dissemination",
        knowledgeDisseminationDesc: "Sharing information on crop management, pest control, market prices, and agritech solutions to address immediate challenges.",
        marketAccess: "Market Access",
        marketAccessDesc: "Using platforms like Facebook Marketplace and TikTok for direct-to-consumer sales, bypassing traditional intermediaries.",
        foodSecurity: "Food Security",
        foodSecurityDesc: "Focusing on protecting agricultural resources, preserving vital seeds in the face of conflict, and promoting resilient farming practices.",
        waterScarcity: "Water Scarcity Solutions",
        waterScarcityDesc: "Discussions on advanced irrigation techniques like drip irrigation and hydroponics to tackle the challenge of water scarcity.",
        techInnovations: "Technological Innovations",
        techInnovationsDesc: "Showcasing protected agriculture solutions, greenhouses, and biotechnology to increase year-round productivity.",
        digitalMarketing: "Digital Marketing",
        digitalMarketingDesc: "The emergence of 'agri-influencers' and the use of digital platforms to connect farmers with markets and promote local products.",
        smartAgriculture: "Smart Agriculture",
        smartAgricultureDesc: "Focus on climate-smart interventions and digital technologies to address climate change and enhance environmental resilience.",
        knowledgeExchange_ug: "Knowledge Exchange",
        knowledgeExchangeDesc_ug: "Widespread use of platforms like WhatsApp and YouTube for information on crop varieties, fertilizers, and pest control.",
        marketAccess_ug: "Market Access",
        marketAccessDesc_ug: "Initiatives to connect farmers to broader markets through digital platforms and promote financial inclusion via mobile money.",
        agriPlatformsTitle: "Top Platforms for Farmers",
        whatsappFacebookDesc: "For groups and rapid knowledge exchange.",
        youtubeDesc: "For practical tutorials and modern techniques.",
        instagramDesc_oman: "For visually showcasing agricultural products and innovations.",
        twitterLinkedinDesc_oman: "For discussing policies and technical solutions.",
        whatsappDesc_ug: "The primary tool for communication among farmers in groups.",
        facebookYoutubeDesc_ug: "For sharing information and visual tutorials.",
        sectionTitleCalendar: "Professional Content Calendar",
        calendarIntro: "Explore the most active days and hours in {country}, and get creative content ideas tailored to audience interests. Green days are the most active overall. Click a day to see suggestions.",
        weeklyHoursTitle: "Weekly Active Hours Overview:",
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        modalTitle: "Suggestions for {month} {day}",
        modalActiveHours: "Active Hours for this Day:",
        modalNoActiveHours: "No prominent active times noted for this day.",
        modalSuggestedPosts: "Posts for {platform}:",
        modalEvents: "Events on this day:",
        modalNoContent: "No specific content suggestions for this day or filter. Broader creative ideas may apply.",
        footerPreparedBy: "Prepared by Brandi for Seedtech"
    },
    ar: {
        mainTitle: "تحليل وسائل التواصل الاجتماعي وتقويم المحتوى لـ Seedtech",
        mainSubtitle: "استكشف المشهد الرقمي في السودان وعُمان وأوغندا",
        sudan: "السودان",
        oman: "عُمان",
        uganda: "أوغندا",
        all: "الكل",
        sectionTitleLandscape: "نظرة عامة على المشهد الرقمي",
        landscapeIntro_sudan: "يتميز المشهد الرقمي في السودان بالهيمنة شبه الكاملة لفيسبوك، مدعومًا بميزة 'الوضع المجاني'، مما يجعله شريان حياة للمعلومات. الوصول عبر الهاتف المحمول هو القاعدة الأساسية، مما يوجه استراتيجيات المحتوى نحو البساطة وسهولة الوصول.",
        landscapeIntro_oman: "تتميز عُمان ببيئة رقمية ناضجة مع نسبة انتشار عالية للإنترنت. يتوزع المستخدمون على عدة منصات رئيسية، مع تفضيل واضح للمحتوى المرئي عالي الجودة والمحتوى الذي يعكس الثقافة المحلية.",
        landscapeIntro_uganda: "المشهد الرقمي في أوغندا متنوع ويقوده الشباب إلى حد كبير. يتصدر TikTok المشاركة. يجب أن تكون النبرة تمكينية وعملية وطموحة، تحتفي بالابتكار المتاح ورحلة التحول من زراعة الكفاف إلى مشاريع الخضروات التجارية.",
        statTitleInternet: "انتشار الإنترنت",
        statTitleSocial: "مستخدمو وسائل التواصل",
        statTitleInsight: "رؤية أساسية",
        chartTitle: "توزيع حصة السوق للمنصات",
        marketShareText_sudan: "يستحوذ فيسبوك على حصة سوقية تقارب 90٪، مما يجعله القناة الأساسية للاتصال الرقمي. يأتي تويتر في المرتبة الثانية بفارق كبير، يليه يوتيوب وإنستغرام وبينترست ولينكد إن بحصص أصغر بكثير.",
        marketShareText_oman: "يقود فيسبوك السوق ولكن بهيمنة أقل، مع وجود قوي جدًا لتويتر وإنستغرام، يليهما بينترست ويوتيوب ولينكد إن. يتطلب هذا التنوع استراتيجية متعددة المنصات للوصول إلى شرائح الجمهور المختلفة.",
        marketShareText_uganda: "يتصدر تويتر حصة السوق، يليه فيسبوك وبينترست، ثم يوتيوب وإنستغرام ولينكد إن. يعكس هذا التنوع تفضيلات جمهور شاب ونشط رقميًا، مما يجعله سوقًا ديناميكيًا للتسويق الرقمي.",
        sectionTitleBehavior: "سلوك المستخدم وأنماط التفاعل",
        behaviorIntro: "هنا، نستكشف الأوقات التي يكون فيها المستخدمون أكثر نشاطًا وأنواع المحتوى التي تحقق أعلى تفاعل. فهم هذه الأنماط هو مفتاح التواصل الفعال مع الجمهور المحلي.",
        peakTimesTitle: "أوقات الذروة للنشاط (تقديري)",
        engagingContentTitle: "المحتوى الأكثر تفاعلاً",
        visualContent: "محتوى مرئي",
        breakingNews: "أخبار عاجلة",
        politicalDiscourse: "نقاش سياسي",
        humorSatire: "فكاهة وسخرية",
        localContent: "محتوى محلي",
        personalStories: "قصص شخصية",
        visualStorytelling: "سرد قصصي مرئي",
        shortFormVideo: "فيديو قصير",
        influencerMarketing: "تسويق عبر المؤثرين",
        thoughtLeadership: "قيادة فكرية",
        directEngagement: "تفاعل مباشر",
        videoContent: "محتوى فيديو",
        liveStreaming: "بث مباشر",
        interactiveContent: "محتوى تفاعلي",
        storytelling: "سرد القصص",
        educationalContent: "محتوى تعليمي",
        sectionTitleAgri: "الزراعة في العصر الرقمي",
        agriIntro_sudan: "في السودان، تُستخدم وسائل التواصل الاجتماعي كأداة حيوية للإرشاد الزراعي والوصول إلى الأسواق، خاصة في ظل التحديات التي يفرضها النزاع. تسهل المنصات تبادل المعرفة حول تقنيات الزراعة المرنة.",
        agriIntro_oman: "في عُمان، يركز المحتوى الزراعي الرقمي على مواجهة التحديات البيئية مثل ندرة المياه. هناك اهتمام كبير بالابتكارات التكنولوجية مثل الزراعة المحمية والري الذكي لتعزيز الأمن الغذائي.",
        agriIntro_uganda: "في أوغندا، يتمحور الحوار الزراعي الرقمي حول استخدام التكنولوجيا لمواجهة التهديدات المناخية. هناك تركيز قوي على برامج الرقمنة والشمول المالي لتمكين المزارعين في المناطق الريفية.",
        agriTopicsTitle: "أهم المواضيع الزراعية",
        agriTopicsSubtitle: "انقر على موضوع لاستكشاف المزيد من التفاصيل.",
        knowledgeDissemination: "نشر المعرفة",
        knowledgeDisseminationDesc: "مشاركة المعلومات حول إدارة المحاصيل ومكافحة الآفات وأسعار السوق والحلول التقنية الزراعية لمواجهة التحديات الفورية.",
        marketAccess: "الوصول إلى الأسواق",
        marketAccessDesc: "استخدام منصات مثل فيسبوك ماركت بليس وتيك توك للمبيعات المباشرة للمستهلكين، متجاوزين الوسطاء التقليديين.",
        foodSecurity: "الأمن الغذائي",
        foodSecurityDesc: "التركيز على حماية الموارد الزراعية، والحفاظ على البذور الحيوية في مواجهة النزاع، وتعزيز ممارسات الزراعة المرنة.",
        waterScarcity: "حلول ندرة المياه",
        waterScarcityDesc: "مناقشات حول تقنيات الري المتقدمة مثل الري بالتنقيط والزراعة المائية لمواجهة تحدي ندرة المياه.",
        techInnovations: "الابتكارات التكنولوجية",
        techInnovationsDesc: "عرض حلول الزراعة المحمية، والبيوت البلاستيكية، والتكنولوجيا الحيوية لزيادة الإنتاجية على مدار العام.",
        digitalMarketing: "التسويق الرقمي",
        digitalMarketingDesc: "ظهور 'المؤثرين الزراعيين' واستخدام المنصات الرقمية لربط المزارعين بالأسواق والترويج للمنتجات المحلية.",
        smartAgriculture: "الزراعة الذكية",
        smartAgricultureDesc: "التركيز على التدخلات الذكية مناخياً والتقنيات الرقمية لمواجهة تغير المناخ وتعزيز المرونة البيئية.",
        knowledgeExchange_ug: "تبادل المعرفة",
        knowledgeExchangeDesc_ug: "استخدام واسع النطاق لمنصات مثل واتساب ويوتيوب للحصول على معلومات حول أصناف المحاصيل والأسمدة ومكافحة الآفات.",
        marketAccess_ug: "الوصول إلى الأسواق",
        marketAccessDesc_ug: "مبادرات لربط المزارعين بأسواق أوسع عبر المنصات الرقمية وتعزيز الشمول المالي عبر الأموال المحمولة.",
        agriPlatformsTitle: "أفضل المنصات للمزارعين",
        whatsappFacebookDesc: "للمجموعات وتبادل المعرفة السريع.",
        youtubeDesc: "للدروس التعليمية العملية والتقنيات الحديثة.",
        instagramDesc_oman: "لعرض المنتجات والابتكارات الزراعية بشكل مرئي.",
        twitterLinkedinDesc_oman: "لمناقشة السياسات والحلول التقنية.",
        whatsappDesc_ug: "الأداة الأساسية للتواصل بين المزارعين في المجموعات.",
        facebookYoutubeDesc_ug: "لمشاركة المعلومات والدروس المرئية.",
        sectionTitleCalendar: "تقويم المحتوى الاحترافي",
        calendarIntro: "استكشف الأيام والساعات الأكثر نشاطًا في {country}، واحصل على أفكار محتوى إبداعية مصممة خصيصًا لاهتمامات الجمهور. الأيام الخضراء هي الأكثر نشاطًا بشكل عام. انقر على يوم لرؤية الاقتراحات.",
        weeklyHoursTitle: "نظرة عامة على ساعات النشاط الأسبوعية:",
        weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        dayNames: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
        months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
        modalTitle: "اقتراحات ليوم {day} {month}",
        modalActiveHours: "ساعات النشاط لهذا اليوم:",
        modalNoActiveHours: "لا توجد أوقات نشاط بارزة مسجلة لهذا اليوم.",
        modalSuggestedPosts: "منشورات مقترحة لـ {platform}:",
        modalEvents: "أحداث في هذا اليوم:",
        modalNoContent: "لا توجد اقتراحات محتوى محددة لهذا اليوم أو الفلتر. قد تنطبق أفكار إبداعية أوسع.",
        footerPreparedBy: "تم الإعداد بواسطة براندي لصالح سيدتك"
    }
};